name: flutter_articles
description: A Flutter app to display articles by categories.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  shared_preferences: ^2.5.4
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
